[versions]
    minecraft = '1.21.5'
    fabric-loader = "0.16.14"

    fabric = "0.120.0+1.21.5"

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'fabric-loader' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }